<wsdl:definitions name="RAAF" targetNamespace="http://example.com/RAAF"
                  xmlns:woza="http://example.com/RAAF" xmlns:zoan="http://example.com/payloadSchema"
                  xmlns:xoan="http://example.com/fighterSchema"
                  xmlns:coan="http://example.com/weaponSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
  <xsd:schema>
      <xsd:import namespace="http://example.com/fighterSchema" schemaLocation="../schema/Fighters.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://example.com/weaponSchema" schemaLocation="../schema/Weapons.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://example.com/payloadSchema" schemaLocation="../schema/Payload.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="getFighterRequestMessage">
    <wsdl:part name="requestPart" element="xoan:getFighterRequest"/>
  </wsdl:message>
  <wsdl:message name="getWeaponRequestMessage">
    <wsdl:part name="requestPart" element="coan:getWeaponRequest"/>
  </wsdl:message>
  <wsdl:message name="getPayloadResponseMessage">
    <wsdl:part name="responsePart" element="zoan:getPayloadResponse"/>
  </wsdl:message>
  <wsdl:portType name="RAAFPortType">
    <wsdl:operation name="getPayload">
      <!--
      <wsdl:input message="woza:getWeaponRequestMessage"/>
      <wsdl:output message="woza:getPayloadResponseMessage"/>
      -->
      <wsdl:input message="woza:getFighterRequestMessage"/>
      <wsdl:output message="woza:getPayloadResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RAAFBinding" type="woza:RAAFPortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="getPayload">
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RAAF">
    <wsdl:port name="NameServicePortTypePort" binding="woza:RAAFBinding">
      <soap:address location="http://www.example.com"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>